version: 0.2 
phases:
 install:
  runtime-versions:
   nodejs: 12
  commands:
   - echo "Installing dependencies..."
   - npm install 
   - npm install -g @angular/cli@10.0.8
  build:
   commands:
    - echo "Building Angular project..."
    - ng build --prod
  post_build:
   commands:
    - echo "Updating files in the s3 bucket..."
    - aws s3 synce dist/github-s3-angular-app/ s3://agular-demo-app --delete
